AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'glue-test-${AWS::AccountId}'
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties: 
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub glue-database
  IcebergTable:
    Type: AWS::Glue::Table
    Properties: 
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: "product_details"
        StorageDescriptor:
          Columns:
            - Name: "product_id"
              Type: "string"
            - Name: "manufacture_name"
              Type: "string"
            - Name: "product_rating"
              Type: "int"
          Location: !Sub "s3://${S3Bucket}/"
        TableType: "EXTERNAL_TABLE"
      OpenTableFormatInput:
        IcebergInput:
          MetadataOperation: "CREATE"
          Version: "2"
  GlueTableOptimizer:
    Type: AWS::Glue::TableOptimizer
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableName: !Ref IcebergTable
      Type: "compaction"
      TableOptimizerConfiguration:
        RoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/iceberg-compaction'
        Enabled: True
